# Generated by Django 5.1.7 on 2025-05-08 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authe", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryOutlay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "limit",
                    models.IntegerField(default=0, verbose_name="Процент лимита"),
                ),
            ],
            options={
                "verbose_name": "Категория расхода",
                "verbose_name_plural": "Категории расходов",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=250, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "education_type",
                    models.CharField(
                        choices=[("bachelor", "Bachelor"), ("magister", "Magister")],
                        default="bachelor",
                        max_length=10,
                        verbose_name="Тип образования",
                    ),
                ),
                ("grant", models.BooleanField(default=False, verbose_name="Грант")),
                (
                    "contract",
                    models.BooleanField(default=False, verbose_name="Контракт"),
                ),
                ("evening", models.BooleanField(default=False, verbose_name="Вечер")),
                (
                    "extramural",
                    models.BooleanField(default=False, verbose_name="Заочный"),
                ),
            ],
            options={
                "verbose_name": "Факультет",
                "verbose_name_plural": "Факультеты",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Название сезона",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Начало сезона"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Конец сезона"
                    ),
                ),
                ("closed", models.BooleanField(default=False, verbose_name="Закрыто")),
            ],
            options={
                "verbose_name": "Сезон",
                "verbose_name_plural": "Сезоны",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="Название Государства"
                    ),
                ),
            ],
            options={
                "verbose_name": "Государство",
                "verbose_name_plural": "Государствa",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "passport_series",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        null=True,
                        verbose_name="Серия паспорта",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=14, verbose_name="Номер телефона"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("possible", "Possible"),
                            ("canceled", "Canceled"),
                            ("closed", "Closed"),
                        ],
                        default="lead",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("telegram", "Telegram"),
                            ("sms", "SMS"),
                            ("facebook", "Facebook"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=11,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "is_checked",
                    models.BooleanField(default=False, verbose_name="Проверено"),
                ),
                (
                    "is_signing_at",
                    models.DateField(blank=True, null=True, verbose_name="Подписан"),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authe.user",
                        verbose_name="Администратор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лид",
                "verbose_name_plural": "Лиды",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("comment", models.TextField(verbose_name="Коментарий")),
                (
                    "lead_status",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Лид статус"
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_comment",
                        to="authe.user",
                        verbose_name="Администратор",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_comment",
                        to="lead.lead",
                        verbose_name="Лид",
                    ),
                ),
            ],
            options={
                "verbose_name": "Коментарий",
                "verbose_name_plural": "Коментарии",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="Outcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Описание"),
                ),
                ("amount", models.FloatField(default=0, verbose_name="Сумма")),
                (
                    "type",
                    models.IntegerField(
                        choices=[(0, "Cash"), (1, "Card"), (2, "Bank"), (3, "Online")],
                        default=0,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "accountant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authe.user",
                        verbose_name="Бухгалтер",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lead.categoryoutlay",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расход",
                "verbose_name_plural": "Расходы",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="SeasonFacultyLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("grant", models.PositiveIntegerField(default=0, verbose_name="Грант")),
                (
                    "contract",
                    models.PositiveIntegerField(default=0, verbose_name="Контракт"),
                ),
                (
                    "evening",
                    models.PositiveIntegerField(default=0, verbose_name="Вечер"),
                ),
                (
                    "extramural",
                    models.PositiveIntegerField(default=0, verbose_name="Заочный"),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lead.faculty",
                        verbose_name="Факультет",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="faculty_limit",
                        to="lead.season",
                        verbose_name="Сезон",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сезонный лимит факультета",
                "verbose_name_plural": "Сезонные границы факультета",
                "ordering": ("created_at",),
            },
        ),
        migrations.AddField(
            model_name="season",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lead.state",
                verbose_name="Государство",
            ),
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "education_type",
                    models.CharField(
                        choices=[("bachelor", "Bachelor"), ("magister", "Magister")],
                        default="bachelor",
                        max_length=10,
                    ),
                ),
                (
                    "study_format",
                    models.CharField(
                        choices=[
                            ("grant", "Grant"),
                            ("contract", "Contract"),
                            ("evening", "Evening"),
                            ("extramural", "Extramural"),
                        ],
                        default="contract",
                        max_length=20,
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Номер телефона"),
                ),
                (
                    "passport_series",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        null=True,
                        verbose_name="Серия паспорта",
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authe.user",
                        verbose_name="Администратор",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_faculty",
                        to="lead.faculty",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lead.season",
                        verbose_name="Сезон",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lead.state",
                        verbose_name="Государство",
                    ),
                ),
            ],
            options={
                "verbose_name": "Студент",
                "verbose_name_plural": "Студенты",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.IntegerField(
                        choices=[(0, "Cash"), (1, "Card"), (2, "Bank"), (3, "Online")],
                        default=3,
                        verbose_name="Способ оплаты",
                    ),
                ),
                ("uploader_amount", models.FloatField(default=0)),
                ("amount", models.FloatField(verbose_name="Сумма")),
                (
                    "check_file",
                    models.FileField(upload_to="checks", verbose_name="Чек"),
                ),
                (
                    "is_payed",
                    models.CharField(
                        choices=[
                            ("pending", "PENDING"),
                            ("payed", "PAYED"),
                            ("canceled", "CANCELED"),
                        ],
                        default="pending",
                        max_length=100,
                        verbose_name="Оплачено",
                    ),
                ),
                (
                    "comment",
                    models.CharField(max_length=500, verbose_name="Коментарий"),
                ),
                (
                    "check_uploader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authe.user",
                        verbose_name="Загрузчик чека",
                    ),
                ),
                (
                    "confirmatory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmatory_user",
                        to="authe.user",
                        verbose_name="Подтверждающий",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lead.student",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оплата",
                "verbose_name_plural": "Оплаты",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="Название университета"
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="state_universities",
                        to="lead.state",
                        verbose_name="Государство",
                    ),
                ),
            ],
            options={
                "verbose_name": "Университет",
                "verbose_name_plural": "Университеты",
                "ordering": ("created_at",),
            },
        ),
        migrations.AddField(
            model_name="student",
            name="university",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lead.university",
                verbose_name="Университет",
            ),
        ),
        migrations.AddField(
            model_name="season",
            name="university",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lead.university",
                verbose_name="Университет",
            ),
        ),
        migrations.AddField(
            model_name="faculty",
            name="university",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uni_faculty",
                to="lead.university",
                verbose_name="Университет",
            ),
        ),
    ]
