# Generated by Django 5.1.7 on 2025-05-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('full_name', models.CharField(max_length=100, verbose_name='Полное имя')),
                ('role', models.IntegerField(choices=[(1, 'SuperUser'), (2, 'HR'), (3, 'Accountant'), (4, 'Admin')], default=4, verbose_name='Роль')),
                ('fixed_salary', models.FloatField(default=0, verbose_name='Фиксированная зарплата')),
                ('phone_number', models.CharField(max_length=14, verbose_name='Номер телефона')),
                ('status', models.IntegerField(choices=[(0, 'Blocked'), (1, 'Active')], default=1, verbose_name='Статус')),
                ('lead_number', models.PositiveIntegerField(default=0, verbose_name='Количество лидов')),
                ('login_time', models.DateTimeField(blank=True, null=True, verbose_name='Время входа')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
